Fix pointer detection for python compiler
%p line must come before other things that match any leading whitespace.

Use %m in %+C line to be more clear that we want to capture that line as output.

Remove the other %Z case since it seems to be the same and it breaks my
test cases.

I should really take these and make a plugin with tests.

Test
Use these outputs to get good-looking quickfix:

== Syntax ==

Traceback (most recent call last):
  File "C:\Users\idbrii\scoop\apps\python39\current\lib\runpy.py", line 158, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\code\proj\config.py", line 198
    conf_lua = [line for line in f if if not comment.match(line)]
                                      ^
SyntaxError: invalid syntax

== Runtime ==

Traceback (most recent call last):
  File "C:\Users\idbrii\scoop\apps\python39\current\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\code\proj\config.py", line 319, in <module>
    filename.fun()
AttributeError: 'NoneType' object has no attribute 'fun'

== Doctest ==

**********************************************************************
File "C:\code\proj\config.py", line 294, in __main__.init_config_assistant
Failed example:
    print(2)
Expected:
    5
Got:
    2
**********************************************************************
1 items had failures:
   1 of   1 in __main__.init_config_assistant
***Test Failed*** 1 failures.

When running these from :AsyncMake, I don't see the message for each
line until :copen again since asyncrun is populating one line at a time
and vim doesn't reparse for that.